
version: 2

models:
  - name: cost_example
    description: "An example"
    columns:
      - name: resource_type
        description: "Type of resource used."
        tests:
          - not_null
  - name: cost_allocation_incremental
    description: "solution"
    columns:
      - name: resource_type
        description: "Type of resource used."
        tests:
          - accepted_values:
                values: [ 'compute', 'storage', 'network', 'monitoring' ]